src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[Vich\Uploadable]
class Article implements \Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(length: 255)]
    private ?string $articleImageName = "";

    #[Vich\UploadableField(mapping: 'article', fileNameProperty: 'articleImageName')]
    private ?File $articleImage = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $write_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getArticleImageName(): ?string
    {
        return $this->articleImageName;
    }

    public function setArticleImageName(?string $articleImageName): static
    {
        $this->articleImageName = $articleImageName;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|null $articleImage
     */
    public function setArticleImage(?File $articleImage = null): void
    {
        $this->articleImage = $articleImage;

        if (null !== $articleImage) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getArticleImage(): ?File
    {
        return $this->articleImage;
    }

    public function serialize()
    {
        return $this->__serialize();
    }

    public function unserialize(string $data)
    {
        return $this->unserialize($data);
    }

    public function __serialize(): array
    {
        return ["id" => $this->getId(),
            "title" => $this->getTitle(),
            "content" => $this->getContent()];
    }

    public function __unserialize(array $data): void
    {
        $this->id = $data["id"];
        $this->setTitle($data["title"]);
        $this->setContent($data["content"]);
    }

    public function getWriteDate(): ?\DateTimeInterface
    {
        return $this->write_date;
    }

    public function setWriteDate(\DateTimeInterface $write_date): static
    {
        $this->write_date = $write_date;

        return $this;
    }
}

src/Entity/WikiCategory.php
<?php

namespace App\Entity;

use App\Repository\WikiCategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;

use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: WikiCategoryRepository::class)]
#[Vich\Uploadable]
class WikiCategory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $cat_url = null;

    #[ORM\Column(length: 255)]
    private ?string $catImageName = "";

    #[Vich\UploadableField(mapping: 'wiki_icon', fileNameProperty: 'catImageName')]
    private ?File $catImage = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'wikiCategory', targetEntity: WikiPage::class, cascade: ['remove'])]
    private Collection $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCatUrl(): ?string
    {
        return $this->cat_url;
    }

    public function setCatUrl(string $cat_url): static
    {
        $this->cat_url = $cat_url;

        return $this;
    }

    public function getCatImageName(): ?string
    {
        return $this->catImageName;
    }

    public function setCatImageName(?string $catImageName): static
    {
        $this->catImageName = $catImageName;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|null $catImage
     */
    public function setCatImage(?File $catImage = null): void
    {
        $this->catImage = $catImage;

        if (null !== $catImage) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getCatImage(): ?File
    {
        return $this->catImage;
    }

    /**
     * @return Collection<int, WikiPage>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(WikiPage $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
            $page->setWikiCategory($this);
        }

        return $this;
    }

    public function removePage(WikiPage $page): static
    {
        if ($this->pages->removeElement($page)) {
            // set the owning side to null (unless already changed)
            if ($page->getWikiCategory() === $this) {
                $page->setWikiCategory(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->cat_url;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <!-- FONTAWESOME -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

        <!-- FONTS -->
        <link rel="stylesheet" href="{{ asset('assets/fonts/fonts.css') }}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/themes/monolith.min.css"/>

        <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">

        <meta charset="UTF-8">
        <title>VikingRP - {% block title %}{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>

    <header class="font-semibold flex justify-evenly items-center p-5" style="background-color:#0B0B0B ;font-size: 1.2em; border-bottom: 1px solid rgb(60, 60, 65); position: sticky; top: 0; z-index:10;color:#fff">
        <div class="flex items-center mx-4">
            <a href="{{ path('app_home') }}"><img class="w-24 mx-2" src="{{ asset('assets/img/logo_v.png')}}" alt="VikingRP"></a>
        </div>
        <div class="flex flex-wrap justify-center">
            <a class="mx-4 button_anim show-resp" href="{{ path('wiki_cat') }}" data-aos="zoom-in-down">Wiki <i class="fa-solid fa-book"></i></a>
            <a class="mx-4 button_anim show-resp" href="https://docs.google.com/forms/d/103_Hx0nskww0CVxxVFsvzz_R3TIezevQ6pSUDS6-vfs" target="_blank" data-aos="zoom-in-down">Candidatures <i class="fa-solid fa-file"></i></a>
            <a style="color: rgba(255, 204, 0);" class="mx-4 button_anim show-resp" href="https://fr.tipeee.com/vikingroleplay" target="_blank" data-aos="zoom-in-down"><i class="fa-solid fa-handshake-angle"></i> Nous soutenir</a>
            <div class="flex items-center">
                <h1 class="text-2xl mx-1">{{ playerOnline }}</h1>
                <i style="color: #28CA43;" class="fa-solid fa-wifi fa-fade mx-2"></i>
            </div>
        </div>


        {% if app.user %}
            <div class="relative inline-block">
                <button type="button" class="dropdown inline-flex w-full justify-center gap-x-1.5 mx-4 px-5 py-2" id="menu-button-skin" role="toggle">
                    <img src="https://mineskin.eu/armor/bust/{{ app.user.username }}.png" alt="Tête du joueur {{ app.user.username }}" class="w-8 h-8 mx-1">
                    <h1 class="mx-1 show-resp">MON COMPTE</h1>
                </button>

                <div class="absolute right-0 z-10 mt-2 w-52 hidden bg-neutral-700 dropdown-content" role="content">
                    <div class="py-1">
                        <a href="{{ path('user_profile') }}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" style="color: white">Mon profil</a>
                        {% if is_granted('ROLE_ADMIN')  %}<a href="{{ path('admin') }}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" style="color: orange">Administration <i class="fa-solid fa-gears"></i></a>{% endif %}
                        <a href="{{ path('app_logout') }}" style="color:red" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Déconnexion <i class="fa-solid fa-right-from-bracket"></i></a>
                    </div>
                </div>
            </div>

        {% else %}
            <div class="relative inline-block">
                <button type="button" class="dropdown inline-flex w-full justify-center gap-x-1.5 mx-4 px-5 py-2" id="menu-button-skin" role="toggle">
                    <img src="https://mineskin.eu/armor/bust/Steve.png" alt="Tête du joueur inconnu" class="w-8 h-8 mx-1">
                    <h1 class="mx-1 show-resp">INCONNU</h1>
                </button>

                <div class="absolute right-0 z-10 mt-2 w-52 hidden bg-neutral-700 dropdown-content" role="content">
                    <div class="py-1">
                        <a href="{{ path('app_register') }}" class="block">Inscription</a>
                        <a href="{{ path('app_login') }}" class="block">Connexion</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </header>
    <body>
        <div class="bodyDiv">
        {% block body %}{% endblock %}
        </div>
    </body>

    <footer class="font-bold p-6" style="background-color: black">
        <hr>
        <div class="flex items-center" style="width: 50%; margin: auto; font-size: 1.2em">
            <div style="width: 40%;" class="text-3xl">
                <h1 style="color: #fff">Suivez-nous</h1>
            </div>
            <div style="width: 60%;" class="p-2 justify-evenly flex">
                <a href="https://www.youtube.com/@VikingRoleplay" target="_blank" style="background-color: #fff; border: 1px solid rgb(60, 60, 65); padding: .4em" class="flex justify-center text-center rounded-full">
                    <i style="color:#02040F;" class="fa-brands fa-youtube"></i>
                </a>
                <a href="https://discord.gg/viking-rp-maintenance-535476824734564372" target="_blank" style="background-color: #fff; padding: .4em; border: 1px solid rgb(60, 60, 65);" class="flex justify-center rounded-full">
                    <i style="color:#02040F;" class="fa-brands fa-discord rounded-full"></i>
                </a>
                <a href="https://www.tiktok.com/@vikingroleplay" target="_blank" style="background-color: #fff; padding: .4em; border: 1px solid rgb(60, 60, 65);" class="flex justify-center rounded-full">
                    <i style="color:#02040F;" class="fa-brands fa-tiktok rounded-full"></i>
                </a>
                <!-- <a href="" style="background-color: #fff; height: 4vh; width: 4vh; border: 1px solid rgb(60, 60, 65);" class="flex justify-center rounded-full">
                    <i style="color:#02040F;" class="fa-solid fa-circle-user rounded-full py-2 px-3"></i>
                </a> !-->
                <a href="https://twitter.com/VikingRoleplay" target="_blank" style="background-color: #fff; padding: .4em; border: 1px solid rgb(60, 60, 65);" class="flex justify-center rounded-full">
                    <i style="color:#02040F;" class="fa-brands fa-twitter rounded-full"></i>
                </a>
            </div>
        </div>
        <hr />
        <div class="flex flex-col items-center p-4 justify-center" style="font-weight: 100;">
            <div class="mb-8">
                <img style="width: 200px; filter: hue-rotate(90deg);" src="{{ asset('assets/img/logo_v.png') }}" alt="vigingrp logo">
            </div>
            <div>
                <h1 style="color:rgb(60, 60, 65)">VikingRP n'est pas affilié à Mojang ou Microsoft. Minecraft est une marque déposée de Mojang Studios.</h1>
            </div>
        </div>
    </footer>
    <script defer>
        document.addEventListener('DOMContentLoaded', function() {
            // Get all elements with the 'dropdown' class
            const dropdowns = document.querySelectorAll('.dropdown');

            // Loop through each dropdown and add event listeners
            dropdowns.forEach(function(dropdown) {
                const dropdownButton = dropdown.querySelector('.dropdown-toggle');
                const dropdownMenu = dropdown.querySelector('.absolute');

                // Check if the elements exist before adding event listeners
                if (dropdownButton && dropdownMenu) {
                    dropdownButton.addEventListener('mouseover', function() {
                        console.log("test");
                        dropdownMenu.classList.toggle('hidden');
                    });

                    document.addEventListener('mouseleave', function(event) {
                        if (!dropdownMenu.contains(event.target) && !dropdownButton.contains(event.target)) {
                            dropdownMenu.classList.add('hidden');
                        }
                    });
                }
            });
        });
    </script>
</html>

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}
{% block body %}
    <section id="mainsection" style="background-image: url('{{ asset('assets/img/trailer_image.png') }}')"
             class="flex flex-col justify-center items-center text-white">
        <div class="text-center" style="width: 80%;">
            <h1 data-aos="zoom-in" data-aos-delay="50" class="text-6xl font-extrabold">Bienvenue <?php echo($pseudo)?>
                sur Viking Roleplay</h1>
            <div data-aos="zoom-in" data-aos-delay="100" class="italic mt-4">
                <p>
                    Plongez dans l'univers épique des Vikings avec notre serveur Roleplay dédié. Explorez des terres
                    vastes et mystérieuses, commercez avec d'autres joueurs, et forgez votre propre destin en tant que
                    fier Viking. Que vous soyez un guerrier intrépide ou un commerçant rusé, notre serveur offre une
                    expérience immersive unique.
                </p>
                <p>
                    Rejoignez-nous et embarquez pour une aventure extraordinaire au cœur de l'âge des Vikings.
                </p>
            </div>
        </div>
        <div data-aos="zoom-in" data-aos-delay="150" class="uppercase flex mt-12" style="font-size: 1.2em;">
            <div class="mx-6 font-extrabold px-6 py-2 items-center flex"
                 style="background-color: #ffffff20; border: 1px solid rgb(60, 60, 65);">
                <i style="padding-right: 10px;" class="fa-solid fa-circle-info"></i>
                <a href="#patch">en savoir plus</a>
            </div>
            <div class="mx-6 font-extrabold py-2 px-6 items-center flex"
                 style="background-color: #e19f2750; border: 1px solid rgb(60, 60, 65); padding-right: 20px; padding-left:10px">
                <img class="w-10" src="{{ asset('assets/img/logo.gif') }}" alt="logo animated"/>
                <a href="#">Nous rejoindre</a>
            </div>
        </div>
        <a href="#patch"><i style="opacity: 30%;"
                                               class="fa-solid show-resp fa-chevron-down fa-bounce text-4xl mt-24"></i></a>
    </section>


    <section id="trailer-section" style="background-color:#060606" class="items-center flex p-2">
        <div class="flex justify-center items-center">
            <div class="flex flex-wrap justify-center items-center">
                <div id="text-center" data-aos="zoom-in" class="p-4" style="width: 50%;">
                    <h1 id="text-trailer" class="text-8xl mb-2 italic"
                        style="-webkit-text-stroke: 2px #ffffff50 ;text-shadow: 0 0 30px rgba(255, 204, 0, 0.6); background: linear-gradient(#ffe98d, #e19f27); -webkit-background-clip:text; -webkit-text-fill-color: transparent">
                        TRAILER</h1>
                    <p class="text-2xl text-white">Découvrez l'épopée qui vous attend sur notre serveur Minecraft viking épique !
                        Plongez au cœur d'un monde rempli de mystères, de conquêtes et de légendes. Notre trailer
                        captivant vous transporte à travers des paysages majestueux, des batailles épiques et des
                        constructions impressionnantes !</p>
                </div>
                <div data-aos="zoom-in" class="rounded-lg p-4 flex flex-col items-center">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/wbxIk1bI-mc?si=a0hhzOUdGL--UPKb" title="YouTube video player"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </section>

    <!-- path note section !-->
    <section class="flex flex-col items-center justify-center text-center bg-cover" id="patch"
             style="background-image: linear-gradient(to bottom, #060606, #06060680), url({{ asset('assets/img/bg/2.png') }}); background-repeat:no-repeat; margin: auto;">

        <div data-aos="zoom-in" class="flex flex-col items-center mx-auto text-center" style="width: 42%;">
            <h1 class="text-8xl italic p-3"
                style="-webkit-text-stroke: 2px #ffffff50 ;text-shadow: 0 0 30px rgba(255, 204, 0, 0.6); background: linear-gradient(#ffe98d, #e19f27); -webkit-background-clip:text; -webkit-text-fill-color: transparent">
                NOTES DE PATCH</h1>
        </div>
        <div data-aos="zoom-in" class="mb-12 text-2xl text-white" style="width: 80%;">
            <p>
                Ne manquez aucune des dernières actualités de notre serveur Minecraft RP en suivant les notes de patch
                quotidiennes ici. Embarquez pour des aventures épiques au cœur de notre monde viking !
            </p>
        </div>

        <div class="text-white">
            {% for article in articles %}
                <div class="mt-4 mb-4">
                    <h2>{{ article.title }}</h2>
                    <p>{{ article.content | slice(0, 180) | raw }}</p>
                    <p>{% if article.articleImageName is not null %}<img src="{{ vich_uploader_asset(article) }}">{% endif %}</p>
                    <p class="font-bold">Le {{ article.writeDate.format('d F Y à H:i') }}</p>
                </div>
            {% endfor %}
            <a href="">Voir plus</a>
        </div>
    </section>

{% endblock %}

templates/wiki.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('wiki') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('wiki') }}
{% endblock %}

{% block body %}
    <div style="max-height: 100vh; overflow: scroll">
        {% if wiki is not null %}
            {% for image in wiki.images %}
                <img src="{{ vich_uploader_asset(image, 'wikiImage') }}" style="margin: auto"/>
            {% endfor %}
        {% elseif cats is not null %}
            <div class="container">
            {% for page in cats %}
                    <div class="column">
                        <a href="{{ path('wiki_cat', {cat_url: page.wikiCategory.catUrl, url: page.url}) }}">
                            {% if page.iconImageName is not null %}<img src="{{ vich_uploader_asset(page, "iconImage") }}" alt="icon section {{ page.url }}">{% endif %}
                        </a>
                    </div>
            {% endfor %}
            </div>
        {% else %}
            <div class="container">
                {% for el in list %}
                <div class="column">
                    <a href="{{ el.url }}">
                    {% if el.iconShow %}<img src="{{ vich_uploader_asset(el.icon, el.iconName, el.className) }}" alt="icon section {{ el.name }}">{% endif %}
                    </a>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}